name: deploy

on:
  # Trigger the workflow on push to main branch
  push:
    branches:
      - main

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  build-book:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.4.12"
          enable-cache: true

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          uv venv
          uv pip install -r requirements.txt

      # Build the book
      - name: Build the book
        run: |
          uv run jupyter-book build .
      # Deploy the book's HTML to gh-pages branch
      # - name: Copy images to gh-pages branch
      #   run: |
      #     cp -r book/images _build/html/book/images
      #     find . -type f -exec sed -i 's|book/geospatial/images|../images|g' {} +

      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/html
